### ISSUE TITLE
Data transfer between master and workers

### ISSUE THREAD

**Issue by ramezrafla** [nathanschwarz/meteor-cluster#2]
In my [redis-oplog](https://github.com/ramezrafla/redis-oplog) we use edge-caching to store often-accessed documents and avoid stressing the DB.

I was thinking that in this scenario, we would have workers fetch data (which may be stored on the master), and whatever data they fetch will have to be re-fetched by the master again.

It would be great to add a messaging protocol, such as like this:

```
// Worker side
await const doc = Cluster.sendToMaster({command:'findOne', selector:'<SOMEID>'})
// do something with doc

// Master 
Cluster.onWorkerMessage = function({command, selector}, responseCallback) {
     // our custom function here
     const doc = collection[command](selector)
     responseCallback(doc)
}
```

What do you think? Right now the messaging is very basic, 'I am done' and 'Oops, I messed up' are the only 2 options :)

**Comment by karthage-spartacus** [comment]
I was planning to add a custom Message Handle in a future release.
I will release an update tonight for scheduled tasks.
I will try to work on a custom Message Handle, but it might be later in the week.

**Comment by karthage-spartacus** [comment]
@ramezrafla IPC feature is out with `@2.0.0`
