### ISSUE TITLE
how does Cluster.maxWorkers() relate to galaxy hosting ECUs?

### ISSUE THREAD

**Issue by aon108** [nathanschwarz/meteor-cluster#7]
I'm assuming that 2 ECUs on galaxy would be Cluster.maxWorkers() = 2. 
Or perhaps this would be 4 as each core would have 2 threads.

Would be amazing if you could shed some light on this.

Thank you in advance :)

**Comment by karthage-spartacus** [comment]
You can read about the differences between cores and threads [here](https://www.guru99.com/cpu-core-multicore-thread.html#:~:text=CPU%20cores%20mean%20the%20actual,component%20which%20manages%20the%20tasks.&text=The%20CPU%20is%20fed%20tasks%20from%20a%20thread.).

In your case `Cluster.maxWorkers() = 2`, if you want to be sure, just do a `console.log(Cluster.maxWorkers())`.

A core is a physical component (hardware) which is composed of several sub-components.
threads are parts of the core, they hold data, while the computing unit of the core is handling an other computation.

multi-core !== multi-threading

Hopes that helped.

**Comment by aon108** [comment]
Thank you for getting back to me. It was my bad using "threads", I was meant to say 'logical cores' as your rightly mention multi-core !== multi-threading.
